$path = 'C:\Users\tshopira\OneDrive\Desktop\PROJET\ru-platform\resources\views\ru.blade.php'
$content = Get-Content $path -Raw

$badAe = [string]([char]0x00C3) + [string]([char]0x00A9)
$badAeGr = [string]([char]0x00C3) + [string]([char]0x00A8)
$badAcd = [string]([char]0x00C3) + [string]([char]0x00A0)
$badAcp = [string]([char]0x00C3) + [string]([char]0x00A2)
$badAcu = [string]([char]0x00C3) + [string]([char]0x00BB)
$badAci = [string]([char]0x00C3) + [string]([char]0x00AF)
$badAco = [string]([char]0x00C3) + [string]([char]0x00B4)
$badAcs = [string]([char]0x00C3) + [string]([char]0x00B6)
$badDot = [string]([char]0x00C2) + [string]([char]0x00B7)
$badEuro = [string]([char]0x00E2) + [string]([char]0x201A) + [string]([char]0x00AC)
$badDash = [string]([char]0x00E2) + [string]([char]0x20AC) + [string]([char]0x201D)
$badApos = [string]([char]0x00E2) + [string]([char]0x20AC) + [string]([char]0x2122)

$goodE = [string]([char]0x00E9)
$goodEGr = [string]([char]0x00E8)
$goodAcd = [string]([char]0x00E0)
$goodAcp = [string]([char]0x00E2)
$goodAcu = [string]([char]0x00FB)
$goodAci = [string]([char]0x00EF)
$goodAco = [string]([char]0x00F4)
$goodAcs = [string]([char]0x00F6)
$goodDot = [string]([char]0x00B7)
$goodEuro = [string]([char]0x20AC)
$goodDash = [string]([char]0x2014)
$goodApos = [string]([char]0x2019)

$content = $content.Replace($badAe, $goodE)
$content = $content.Replace($badAeGr, $goodEGr)
$content = $content.Replace($badAcd, $goodAcd)
$content = $content.Replace($badAcp, $goodAcp)
$content = $content.Replace($badAcu, $goodAcu)
$content = $content.Replace($badAci, $goodAci)
$content = $content.Replace($badAco, $goodAco)
$content = $content.Replace($badAcs, $goodAcs)
$content = $content.Replace($badDot, $goodDot)
$content = $content.Replace($badEuro, $goodEuro)
$content = $content.Replace($badDash, $goodDash)
$content = $content.Replace($badApos, $goodApos)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($path, $content, $utf8NoBom)
